# DataFrame Practice

In [50]:
import numpy as np
import pandas as pd

# Create Dataframe Manually

In [2]:
dt=pd.read_csv(r"C:\Users\HP\Desktop\Python for Data Science\Pandas Dataframe\youtube_shorts_performance_dataset.csv")
dt

,video_id,title,duration_sec,hashtags_count,views,likes,comments,shares,upload_hour,category
0,vid_1000,Short Video #0,43,9,198775,21933,3228,400,8,Tech
1,vid_1001,Short Video #1,56,2,290336,20063,3719,1942,16,Comedy
2,vid_1002,Short Video #2,33,6,264206,37032,3228,1817,7,Food
3,vid_1003,Short Video #3,19,9,85076,27269,2371,980,1,Lifestyle
4,vid_1004,Short Video #4,47,8,90780,8041,2891,1109,23,Tech
...,...,...,...,...,...,...,...,...,...,...
295,vid_1295,Short Video #295,15,3,248940,23810,488,1247,12,Tech
296,vid_1296,Short Video #296,32,4,366340,29586,46,1548,8,Travel
297,vid_1297,Short Video #297,29,3,434027,6471,3359,1069,21,Comedy
298,vid_1298,Short Video #298,54,4,318623,6459,4873,1690,14,Food
299,vid_1299,Short Video #299,27,6,217464,40731,4806,1136,13,Tech

# Attributes

In [5]:
dt.shape

(300, 10)

In [6]:
dt.index

RangeIndex(start=0, stop=300, step=1)

In [7]:
dt.columns

Index(['video_id', 'title', 'duration_sec', 'hashtags_count', 'views', 'likes',
       'comments', 'shares', 'upload_hour', 'category'],
      dtype='str')

In [8]:
dt.values

array([['vid_1000', 'Short Video #0', 43, ..., 400, 8, 'Tech'],
       ['vid_1001', 'Short Video #1', 56, ..., 1942, 16, 'Comedy'],
       ['vid_1002', 'Short Video #2', 33, ..., 1817, 7, 'Food'],
       ...,
       ['vid_1297', 'Short Video #297', 29, ..., 1069, 21, 'Comedy'],
       ['vid_1298', 'Short Video #298', 54, ..., 1690, 14, 'Food'],
       ['vid_1299', 'Short Video #299', 27, ..., 1136, 13, 'Tech']],
      shape=(300, 10), dtype=object)

# Methods

In [9]:
dt.head(3)

,video_id,title,duration_sec,hashtags_count,views,likes,comments,shares,upload_hour,category
0,vid_1000,Short Video #0,43,9,198775,21933,3228,400,8,Tech
1,vid_1001,Short Video #1,56,2,290336,20063,3719,1942,16,Comedy
2,vid_1002,Short Video #2,33,6,264206,37032,3228,1817,7,Food

In [10]:
dt.tail(3)

,video_id,title,duration_sec,hashtags_count,views,likes,comments,shares,upload_hour,category
297,vid_1297,Short Video #297,29,3,434027,6471,3359,1069,21,Comedy
298,vid_1298,Short Video #298,54,4,318623,6459,4873,1690,14,Food
299,vid_1299,Short Video #299,27,6,217464,40731,4806,1136,13,Tech

In [12]:
dt.sample()

,video_id,title,duration_sec,hashtags_count,views,likes,comments,shares,upload_hour,category
53,vid_1053,Short Video #53,18,5,221411,22674,2872,920,16,Food

In [13]:
dt.info()

<class 'pandas.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   video_id        300 non-null    str
 1   title           300 non-null    str
 2   duration_sec    300 non-null    int64
 3   hashtags_count  300 non-null    int64
 4   views           300 non-null    int64
 5   likes           300 non-null    int64
 6   comments        300 non-null    int64
 7   shares          300 non-null    int64
 8   upload_hour     300 non-null    int64
 9   category        300 non-null    str
dtypes: int64(7), str(3)
memory usage: 23.6 KB

In [14]:
dt.describe()

,duration_sec,hashtags_count,views,likes,comments,shares,upload_hour
count,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000
mean,31.730000,4.343333,245058.166667,23063.126667,2638.296667,999.576667,11.543333
std,16.042912,2.956562,141338.982093,14597.458220,1416.827287,564.410105,6.814414
min,5.000000,0.000000,1404.000000,109.000000,40.000000,2.000000,0.000000
25%,18.000000,2.000000,129620.500000,10342.000000,1445.750000,516.250000,6.000000
50%,32.000000,4.000000,255962.000000,21779.500000,2863.500000,988.000000,12.000000
75%,45.000000,7.000000,356805.000000,36706.500000,3761.000000,1463.750000,17.000000
max,59.000000,9.000000,499401.000000,49923.000000,4971.000000,1998.000000,23.000000

In [15]:
dt.value_counts()

video_id  title             duration_sec  hashtags_count  views   likes  comments  shares  upload_hour  category
vid_1000  Short Video #0    43            9               198775  21933  3228      400     8            Tech         1
vid_1001  Short Video #1    56            2               290336  20063  3719      1942    16           Comedy       1
vid_1002  Short Video #2    33            6               264206  37032  3228      1817    7            Food         1
vid_1003  Short Video #3    19            9               85076   27269  2371      980     1            Lifestyle    1
vid_1004  Short Video #4    47            8               90780   8041   2891      1109    23           Tech         1
                                                                                                                    ..
vid_1295  Short Video #295  15            3               248940  23810  488       1247    12           Tech         1
vid_1296  Short Video #296  32            4               366340  29586  46        1548    8            Travel       1
vid_1297  Short Video #297  29            3               434027  6471   3359      1069    21           Comedy       1
vid_1298  Short Video #298  54            4               318623  6459   4873      1690    14           Food         1
vid_1299  Short Video #299  27            6               217464  40731  4806      1136    13           Tech         1
Name: count, Length: 300, dtype: int64

In [16]:
dt["hashtags_count"].value_counts()

hashtags_count
0    39
2    38
9    35
4    33
3    31
6    28
7    26
8    25
5    23
1    22
Name: count, dtype: int64

In [17]:
dt.sort_values(["hashtags_count","likes","comments","shares"],ascending=[1,0,0,1])

,video_id,title,duration_sec,hashtags_count,views,likes,comments,shares,upload_hour,category
101,vid_1101,Short Video #101,30,0,283703,49377,2262,1165,19,Education
188,vid_1188,Short Video #188,46,0,63292,47462,2573,579,8,Food
167,vid_1167,Short Video #167,43,0,57178,46614,1409,1122,12,Travel
228,vid_1228,Short Video #228,53,0,317076,41932,4225,795,11,Comedy
24,vid_1024,Short Video #24,42,0,204664,41340,2265,994,21,Food
...,...,...,...,...,...,...,...,...,...,...
131,vid_1131,Short Video #131,12,9,484685,3912,1823,10,20,Lifestyle
256,vid_1256,Short Video #256,36,9,482680,2292,153,570,16,Lifestyle
200,vid_1200,Short Video #200,32,9,106570,1442,3180,1218,19,Comedy
98,vid_1098,Short Video #98,51,9,297764,1162,1759,1712,14,Tech
191,vid_1191,Short Video #191,10,9,194752,109,4033,1633,17,Comedy

In [28]:
dt["video_id"].sort_index(ascending=0)

299    vid_1299
298    vid_1298
297    vid_1297
296    vid_1296
295    vid_1295
         ...
4      vid_1004
3      vid_1003
2      vid_1002
1      vid_1001
0      vid_1000
Name: video_id, Length: 300, dtype: str

In [32]:
dt.set_index("hashtags_count")

,video_id,title,duration_sec,views,likes,comments,shares,upload_hour,category
hashtags_count,,,,,,,,,
9,vid_1000,Short Video #0,43,198775,21933,3228,400,8,Tech
2,vid_1001,Short Video #1,56,290336,20063,3719,1942,16,Comedy
6,vid_1002,Short Video #2,33,264206,37032,3228,1817,7,Food
9,vid_1003,Short Video #3,19,85076,27269,2371,980,1,Lifestyle
8,vid_1004,Short Video #4,47,90780,8041,2891,1109,23,Tech
...,...,...,...,...,...,...,...,...,...
3,vid_1295,Short Video #295,15,248940,23810,488,1247,12,Tech
4,vid_1296,Short Video #296,32,366340,29586,46,1548,8,Travel
3,vid_1297,Short Video #297,29,434027,6471,3359,1069,21,Comedy
4,vid_1298,Short Video #298,54,318623,6459,4873,1690,14,Food
6,vid_1299,Short Video #299,27,217464,40731,4806,1136,13,Tech

In [33]:
dt.reset_index()

,index,video_id,title,duration_sec,hashtags_count,views,likes,comments,shares,upload_hour,category
0,0,vid_1000,Short Video #0,43,9,198775,21933,3228,400,8,Tech
1,1,vid_1001,Short Video #1,56,2,290336,20063,3719,1942,16,Comedy
2,2,vid_1002,Short Video #2,33,6,264206,37032,3228,1817,7,Food
3,3,vid_1003,Short Video #3,19,9,85076,27269,2371,980,1,Lifestyle
4,4,vid_1004,Short Video #4,47,8,90780,8041,2891,1109,23,Tech
...,...,...,...,...,...,...,...,...,...,...,...
295,295,vid_1295,Short Video #295,15,3,248940,23810,488,1247,12,Tech
296,296,vid_1296,Short Video #296,32,4,366340,29586,46,1548,8,Travel
297,297,vid_1297,Short Video #297,29,3,434027,6471,3359,1069,21,Comedy
298,298,vid_1298,Short Video #298,54,4,318623,6459,4873,1690,14,Food
299,299,vid_1299,Short Video #299,27,6,217464,40731,4806,1136,13,Tech

In [35]:
dt.rename(columns={"video_id":"VIDEO_ID","title":"TITLE"},inplace=True)

In [36]:
dt

,VIDEO_ID,TITLE,duration_sec,hashtags_count,views,likes,comments,shares,upload_hour,category
0,vid_1000,Short Video #0,43,9,198775,21933,3228,400,8,Tech
1,vid_1001,Short Video #1,56,2,290336,20063,3719,1942,16,Comedy
2,vid_1002,Short Video #2,33,6,264206,37032,3228,1817,7,Food
3,vid_1003,Short Video #3,19,9,85076,27269,2371,980,1,Lifestyle
4,vid_1004,Short Video #4,47,8,90780,8041,2891,1109,23,Tech
...,...,...,...,...,...,...,...,...,...,...
295,vid_1295,Short Video #295,15,3,248940,23810,488,1247,12,Tech
296,vid_1296,Short Video #296,32,4,366340,29586,46,1548,8,Travel
297,vid_1297,Short Video #297,29,3,434027,6471,3359,1069,21,Comedy
298,vid_1298,Short Video #298,54,4,318623,6459,4873,1690,14,Food
299,vid_1299,Short Video #299,27,6,217464,40731,4806,1136,13,Tech

In [37]:
dt["duration_sec"].unique()

array([43, 56, 33, 19, 47, 12, 25, 23, 27, 15, 28, 57, 40, 44,  7, 26,  6,
       48, 34, 42, 37, 16, 29, 53, 31, 46, 32, 20, 51, 55, 59, 41, 11, 13,
       22,  8, 18, 54, 30, 24, 39, 21, 10, 58, 38, 14, 35, 52, 49, 45,  5,
        9, 17, 36])

In [39]:
dt.nunique(dropna=False)

VIDEO_ID          300
TITLE             300
duration_sec       54
hashtags_count     10
views             300
likes             299
comments          288
shares            274
upload_hour        24
category            6
dtype: int64

In [40]:
dt["views"].unique()

array([198775, 290336, 264206,  85076,  90780, 153617,  22689, 274318,
       351605, 389318, 366177,  10348, 417930,  39102,  75460, 365778,
        90930,   7801, 104150, 204339, 180208, 155697, 214945, 232915,
       204664, 209124, 438477,   2542, 284821, 178804, 182415,  40081,
       194928, 356249, 220930, 282209, 215532,  89092, 317837, 290106,
        29295,  14807, 436564, 158504, 477501, 239067, 486008, 452070,
       434478, 169152, 395540, 354411, 167981, 221411,  20870, 428794,
       204196, 249683, 235677,  27790, 119874, 288433, 449345, 225786,
       488462,  16485, 307626,  87188,   5748, 218841, 141507, 266853,
       124961,  31355, 187843, 452015, 407332, 157542, 174416, 306062,
       315368,  40298, 343363,  62629, 329184, 493734, 231907, 291160,
        24960, 296735, 214920, 366477, 243804, 377965, 461857, 299539,
       130695, 416916, 297764, 235286, 129148, 283703, 487261, 356540,
       193714, 208611, 284876, 260747,  92362, 424570, 276987, 115065,
       334870,  18640,  53528, 301557, 260214, 315782, 446952, 111133,
       369501, 200938, 151159, 173502, 156576, 401330, 342003, 362801,
       405191,  12023,  22447, 484685, 389043, 287103,  67203, 382300,
       161775,  10337,  47427, 324673, 365167, 347809, 106787, 163993,
       296451, 421571, 497484, 128016, 267979,  21159, 498562, 179677,
       384934, 368760, 432304, 341896, 318428, 320187, 167619, 360151,
        83844,  28532, 166421, 123402, 119012, 439661, 399929,  57178,
        50407, 464556,  51990, 469888, 130473, 459761, 479007, 321285,
       418009, 319714, 227156, 169964,   2015,  62813,  28712, 101497,
       402631, 243926, 113816, 129778,  63292, 286977, 136230, 194752,
       283453, 270114, 335618, 480920, 309684, 152456, 281161, 339024,
       106570, 271846, 394600,   1404, 435159, 179998, 423405, 275907,
       150456, 192172, 361286, 141932, 236365, 343786,  51612, 286718,
       286668, 201244, 274060,   5809, 164273, 185402, 145528, 450613,
       384432,  39765, 429032, 308250, 317076, 411316, 320235,  22949,
       202152, 300888, 177615, 371463,  93193,  37187, 139311, 387598,
       277633, 190089,  62877, 437341, 313066,  95074, 164121,  38131,
       437160, 116765, 337107, 107884, 126917, 287429, 300770, 174880,
       482680, 448087, 282342, 413974,  16254,  45238,   2252, 302908,
       340853, 431657, 486450, 316826, 322638,  82317, 328359,  79587,
       499401,   7949, 239897, 318537, 205625, 139013,  26934, 417602,
       257434, 456102, 338889, 477467, 357600, 316557, 451016, 360383,
       305462, 251875, 464389,  71390, 184401, 254490,  44088, 248940,
       366340, 434027, 318623, 217464])

# How to handle missing values?

In [41]:
dt.isnull().sum()

VIDEO_ID          0
TITLE             0
duration_sec      0
hashtags_count    0
views             0
likes             0
comments          0
shares            0
upload_hour       0
category          0
dtype: int64

In [54]:
Student_dict={
    "Name":["Rajdip","Pritam","Sanjoy"],
    "Age":[27,25,26],
    "Company":["TCS","Deloitte","Cognizant"]
}
D=pd.DataFrame(Student_dict)

In [55]:
D

     Name  Age    Company
0  Rajdip   27        TCS
1  Pritam   25   Deloitte
2  Sanjoy   26  Cognizant

In [57]:
D.iloc[[1,2],[1]]=np.nan
D

     Name   Age    Company
0  Rajdip  27.0        TCS
1  Pritam   NaN   Deloitte
2  Sanjoy   NaN  Cognizant

In [61]:
D1=D.fillna(D["Age"].mean())
D1

     Name   Age    Company
0  Rajdip  27.0        TCS
1  Pritam  27.0   Deloitte
2  Sanjoy  27.0  Cognizant

In [62]:
dt.head(2)

,VIDEO_ID,TITLE,duration_sec,hashtags_count,views,likes,comments,shares,upload_hour,category
0,vid_1000,Short Video #0,43,9,198775,21933,3228,400,8,Tech
1,vid_1001,Short Video #1,56,2,290336,20063,3719,1942,16,Comedy

In [64]:
dt.groupby("TITLE").duration_sec.agg(["max","min","mean","sum"])

                  max  min  mean  sum
TITLE
Short Video #0     43   43  43.0   43
Short Video #1     56   56  56.0   56
Short Video #10    15   15  15.0   15
Short Video #100   28   28  28.0   28
Short Video #101   30   30  30.0   30
...               ...  ...   ...  ...
Short Video #95    20   20  20.0   20
Short Video #96    49   49  49.0   49
Short Video #97    22   22  22.0   22
Short Video #98    51   51  51.0   51
Short Video #99    57   57  57.0   57

[300 rows x 4 columns]

In [69]:
dt.groupby(["VIDEO_ID","TITLE"]).agg({
    "duration_sec":["max","sum"],
    "hashtags_count":["mean"]
})

                          duration_sec     hashtags_count
                                   max sum           mean
VIDEO_ID TITLE
vid_1000 Short Video #0             43  43            9.0
vid_1001 Short Video #1             56  56            2.0
vid_1002 Short Video #2             33  33            6.0
vid_1003 Short Video #3             19  19            9.0
vid_1004 Short Video #4             47  47            8.0
...                                ...  ..            ...
vid_1295 Short Video #295           15  15            3.0
vid_1296 Short Video #296           32  32            4.0
vid_1297 Short Video #297           29  29            3.0
vid_1298 Short Video #298           54  54            4.0
vid_1299 Short Video #299           27  27            6.0

[300 rows x 3 columns]

In [75]:
dt.groupby(["TITLE","VIDEO_ID","category"]).likes.agg(["sum","mean"]).unstack()

                               sum                                        \
category                    Comedy Education     Food Lifestyle     Tech
TITLE            VIDEO_ID
Short Video #0   vid_1000      NaN       NaN      NaN       NaN  21933.0
Short Video #1   vid_1001  20063.0       NaN      NaN       NaN      NaN
Short Video #10  vid_1010      NaN       NaN      NaN       NaN      NaN
Short Video #100 vid_1100      NaN       NaN      NaN    6329.0      NaN
Short Video #101 vid_1101      NaN   49377.0      NaN       NaN      NaN
...                            ...       ...      ...       ...      ...
Short Video #95  vid_1095  45640.0       NaN      NaN       NaN      NaN
Short Video #96  vid_1096      NaN       NaN  10367.0       NaN      NaN
Short Video #97  vid_1097      NaN   25389.0      NaN       NaN      NaN
Short Video #98  vid_1098      NaN       NaN      NaN       NaN   1162.0
Short Video #99  vid_1099      NaN   30026.0      NaN       NaN      NaN

                                       mean                               \
category                    Travel   Comedy Education     Food Lifestyle
TITLE            VIDEO_ID
Short Video #0   vid_1000      NaN      NaN       NaN      NaN       NaN
Short Video #1   vid_1001      NaN  20063.0       NaN      NaN       NaN
Short Video #10  vid_1010  12115.0      NaN       NaN      NaN       NaN
Short Video #100 vid_1100      NaN      NaN       NaN      NaN    6329.0
Short Video #101 vid_1101      NaN      NaN   49377.0      NaN       NaN
...                            ...      ...       ...      ...       ...
Short Video #95  vid_1095      NaN  45640.0       NaN      NaN       NaN
Short Video #96  vid_1096      NaN      NaN       NaN  10367.0       NaN
Short Video #97  vid_1097      NaN      NaN   25389.0      NaN       NaN
Short Video #98  vid_1098      NaN      NaN       NaN      NaN       NaN
Short Video #99  vid_1099      NaN      NaN   30026.0      NaN       NaN


category                      Tech   Travel
TITLE            VIDEO_ID
Short Video #0   vid_1000  21933.0      NaN
Short Video #1   vid_1001      NaN      NaN
Short Video #10  vid_1010      NaN  12115.0
Short Video #100 vid_1100      NaN      NaN
Short Video #101 vid_1101      NaN      NaN
...                            ...      ...
Short Video #95  vid_1095      NaN      NaN
Short Video #96  vid_1096      NaN      NaN
Short Video #97  vid_1097      NaN      NaN
Short Video #98  vid_1098   1162.0      NaN
Short Video #99  vid_1099      NaN      NaN

[300 rows x 12 columns]